name: Epic Free Actions

on:
  schedule:
    - cron: "25 2 * * *"
  push:
    branches: [ main ]

env:
  TZ: Asia/Shanghai

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Workflow Repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          playwright install

      - name: Get Games Script
        env: 
          EPIC_EMAIL: ${{ secrets.EPIC_EMAIL }}
          EPIC_PASSWORD: ${{ secrets.EPIC_PASSWORD }}
          QMSG_TOKEN: ${{ secrets.QMSG_TOKEN }}
        run: python get_games_script.py
